status:
  port: 16241

storages:
  - name: main
    plugin: fs
    config:
      directory: /var/lib/yandex/unified_agent/main
      max_partition_size: 10mb
      max_segment_size: 1mb

channels:
  - name: cloud_monitoring
    channel:
      pipe:
        - storage_ref:
            name: main
      output:
        plugin: yc_metrics
        config:
          folder_id: "__FOLDER_ID__"
          iam:
            cloud_meta: {}

routes:
  - input:
      plugin: metrics_pull
      config:
        url: http://localhost:9090/actuator/prometheus
        format:
          prometheus: {}
        namespace: bulletins
        poll_period: 30s
        metric_name_label: sensor
    channel:
      channel_ref:
        name: cloud_monitoring
