---
# Несекретная часть конфигурации приложения.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bulletin-board.name" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bulletin-board.labels" . | nindent 4 }}
data:
  MANAGEMENT_SERVER_PORT: {{ .Values.service.managementPort | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
