{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.storeName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bulletin-board.labels" . | nindent 4 }}
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: {{ .Values.externalSecrets.authorizedKeySecret }}
          key: key.json
{{- end }}
