---
apiVersion: v1
kind: Secret
metadata:
  name: bulletin-secret
  namespace: bulletins
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://<db_host>:6432/bulletins?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "<db_user>"
  SPRING_DATASOURCE_PASSWORD: "<db_password>"
  STORAGE_S3_ACCESSKEY: "<storage_access_key>"
  STORAGE_S3_SECRETKEY: "<storage_secret_key>"
